# Generated by Django 4.2 on 2025-01-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Введите имя пользователя",
                max_length=30,
                null=True,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Введите фамилию пользователя",
                max_length=50,
                null=True,
                verbose_name="Фамилия пользователя",
            ),
        ),
    ]
