# Generated by Django 4.2 on 2025-01-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="id",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="uuid",
            field=models.UUIDField(
                editable=False,
                help_text="Уникальный идентификатор кошелька",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID кошелька",
            ),
        ),
    ]
