# Generated by Django 4.2 on 2025-01-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_alter_wallet_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("DEPOSIT", "Депозит"), ("WITHDRAWAL", "Вывод")],
                        help_text="Выберете тип операции",
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите сумму операции",
                        max_digits=10,
                        verbose_name="Сумма операции",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания операции",
                        verbose_name="Дата создания операции",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Введите кошелек",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.wallet",
                        verbose_name="Кошелек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
            },
        ),
    ]
